# Project: Data Science Interview Questions

# common operations for numpy array

In [115]:
# 1. how to obtain diagonal of a matrix 
AAA = np.arange(9).reshape(3,3)
AAA

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
# diagonal
AAA.diagonal()

array([0, 4, 8])

In [114]:
# diagonal sum 
AAA.diagonal().sum()

12

In [116]:
# 2. flatten a matrix 
AAA.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
# 3. find determinant
np.linalg.det(AAA)

0.0

# Question 1: 
- Given a 4x4 Numpy matrix, reverse the matrix.
- https://towardsdatascience.com/python-data-science-interview-questions-d83f396f9954

In [18]:
# step 0: construct a 4*4 Numpy matrix
import numpy as np
matrix = np.arange(1,17).reshape(4,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
# step 1: to flatten the numpy array 
# use np.array.flatten() for numpy arrays
# use matrix.ravel() for matrix (list)

matrix_flat = matrix.flatten()
matrix_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
# step 2: read the elements backward into a new matrix
matrix_reversed = matrix_flat[::-1]
matrix_reversed

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
# step 3: reshape the matrix back into a 4*4 matrix
matrix_reversed.reshape(4,4)

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

----

# Question 2: How do you multiply two matrics?

# two solutions
1. dot method for numpy array
2. nested for loops for non numpy array

In [36]:
# step 1: numpy array 
A = np.arange(9).reshape(3,3)
B = np.arange(10,19).reshape(3,3)

In [37]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
# step 2: use dot method
result = A.dot(B)

In [41]:
print(result)

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


---

In [25]:
# solution 2: nested for loop for non-numpy array 
X = [
    [1,2,3],
    [2,3,4,],
    [4,3,2]
]

Y = [
    [2,3,4],
    [3,4,6],
    [2,3,5]
]

In [22]:
type(X)

list

In [23]:
# step 1: create a zero matrix to store results
Z = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

In [24]:
Z

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [66]:
# step 2: iterate over rows of X; len(X) returns the number of rows
for i in range(len(X)):
     
    # iterate over columns of Y; len(Y[0]) returns the number of columns of Y
    for j in range(len(Y[0])):
        
        # iterate rows of Y
        for k in range(len(Y)):
            
            Z[i][j] += X[i][k]*Y[k][j]
        
Z

[[14, 20, 31], [21, 30, 46], [21, 30, 44]]

---

# Question 3: How to transpose a matrix? 
Three solutions:
1. nested for loop 
2. using zip
3. numpy.transpose

In [88]:
X = [
    [12,7],
    [1,2],
    [3,4]
]

# Solution 1: nested for loop

In [86]:
# step 1: empty list 
transpose = [
    [0,0,0],
    [0,0,0]
]

In [83]:
# step 2: nested for loop
# iterate through rows 
for i in range(len(X)):
    
    # iterate through columns: # len(transpose) = len(X[0])
    for j in range(len(transpose)): 
        
        # replace elements 
        transpose[j][i] = X[i][j]

In [82]:
for r in transpose: 
    print(r)

[12, 1, 3]
[7, 2, 4]


---

# Solution 2: using zip

In [34]:
matrix = [(1,2,3),(4,5,6),(7,8,9),(10,11,12)]# a list of tuples
matrix

[(1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)]

In [96]:
# unzip the matrix using *
# then, zip it back to a matrix
matrix_transpose = zip(*matrix)

In [97]:
for i in matrix_transpose:
    print(i)

(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


---

# Solution 3: numpy array

In [40]:
X = [
    [12,7],
    [1,2],
    [3,4]
]

In [41]:
type(X)

list

In [42]:
# 3.1 np.transpose()
import numpy as np

transpose = np.transpose(X)
print(transpose)

[[12  1  3]
 [ 7  2  4]]


In [38]:
# 3.2 matrix.T for np.array()
matrix_array = np.array(X)

matrix_array.T

array([[12,  1,  3],
       [ 7,  2,  4]])

In [43]:
type(matrix_array)

numpy.ndarray

---

# Question 4: how to add two Numpy matrices together?

In [6]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

In [7]:
# method1： np.array() --> element-wise addition
import numpy as np 
X_np = np.array(X)
Y_np = np.array(Y)

result = X_np + Y_np
print(result)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [8]:
# method2: nested for loops
result = np.zeros((3,3))

# iterate through rows
for i in range(len(X)):

    #iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j]+Y[i][j]
        
for r in result: 
    print(r)

[17. 15.  4.]
[10. 12.  9.]
[11. 13. 18.]


---

In [44]:
# related question: how to stack matrices vertically?
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

np.vstack((X,Y))

array([[12,  7,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 5,  8,  1],
       [ 6,  7,  3],
       [ 4,  5,  9]])

In [46]:
# horizontal stacking
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

np.hstack((X,Y))

array([[12,  7,  3,  5,  8,  1],
       [ 4,  5,  6,  6,  7,  3],
       [ 7,  8,  9,  4,  5,  9]])